package me.halin.daggerstudy.Dagger2;

import android.content.Context;


import me.halin.daggerstudy.Dagger2.AutoGenerate.DaggerAutoGenerateDemo;
import me.halin.daggerstudy.Dagger2.Base.DaggerBaseDemo;
import me.halin.daggerstudy.Dagger2.Dependencies.DaggerDependenciesDemo;
import me.halin.daggerstudy.Dagger2.InjectMethod.DaggerMethodInjectDemo;
import me.halin.daggerstudy.Dagger2.Named.DaggerNamedDemo;
import me.halin.daggerstudy.Dagger2.Singleton.DaggerSingletonDemo;
import me.halin.fundamental.LogUtil.Logger;


/**
 * Created by 17track on 3/25/16.
 */

public class Dagger2Demo {

    public static void test(Context context) {
        Logger.debug("/*-------------------Dagger2Demo测试开始------------------*/");
//         DaggerBaseDemo.test(context);
//        DaggerMethodInjectDemo.test();
//        DaggerDependenciesDemo.test();
//        DaggerNamedDemo.test();
//        DaggerSingletonDemo.test();
        DaggerAutoGenerateDemo.test();
    }

}
