package me.halin.daggerstudy.Dagger2.AutoGenerate;

import javax.inject.Inject;

import me.halin.fundamental.LogUtil.Logger;

/**
 * Created by Halin on 5/5/16.
 */
public class DaggerAutoGenerateDemo {

    public static void test() {
        //AutoGenerateComponent不设置一个AutoGenerateModule对象,该对象由DaggerAutoGenerateComponent调用AutoGenerateModule的无参构造函数自动生成
        AutoGenerateComponent autoGenerateComponent = DaggerAutoGenerateComponent.builder().build();
        DaggerAutoGenerateDemo demo = new DaggerAutoGenerateDemo();
        autoGenerateComponent.inject(demo);
        Logger.debug("当前时间:%d", demo.currentTime);

    }

    @Inject
    long currentTime;

}
